content/blog/tikv-2.1ga-release-notes.md
@queenypingcap @lucperkins PTAL
Related link: https://github.com/tikv/tikv/releases/tag/v2.1.0
=> content/blog: add TiKV 2.1 GA Release Notes

content/blog/tikv-2.1-more-raft-less-hotspots.md
@queenypingcap @lucperkins PTAL
=> content/blog: add TiKV 2.1 announcement

content/blog/tikv-2.1-more-raft-less-hotspots.md, content/blog/tikv-2.1ga-release-notes.md
=> content/blog: remove body titles

content/docs/security.md, layouts/index.redirects
Create a security document that includes vulnerability disclosure to satisfy https://github.com/tikv/tikv/issues/4263.
=> Create security document

data/adopters.yaml
=> More Adopters

data/adopters.yaml
Updated two newly added adopters (Shopee and BookMyShow)
=> data/adopters.yaml: add new adopters

content/docs/apis.md
Undrafts the APIs document to show various client and how to get started with one of them.
=> Undraft APIs document

config.toml, content/blog/tikv-community-connections.md, layouts/_default/blog/card.html, layouts/partials/blog/post-list.html, layouts/partials/navbar.html
Adds links to our community chat and forum.
=> Add forum & chat

content/docs/concepts/apis.md
Signed-off-by: Ana Hobden <operator@hoverbear.org>
=> Fix go client link

content/deep-dive/key-value-engine/b-tree-vs-lsm.md
Fix broken images on https://tikv.org/deep-dive/key-value-engine/b-tree-vs-lsm/.
=> fix broken images

assets/sass/style.sass, layouts/index.html
See preview here:
https://deploy-preview-37--tikv.netlify.com/
=> Add incubation announcement to landing page

content/blog/cncf-incubating.md
Add a CNCF announce blog post!
=> Add incubating blog post

content/deep-dive/distributed-transaction/optimized-percolator.md
This is a PR with content from @MyonKeminta that was posted on https://github.com/tikv/deep-dive-tikv/pull/32.
=> Add optimized percolator chapter by @MyonKeminta

layouts/deep-dive/single.html, layouts/partials/math.html
=> Add Katex support

content/blog/talent-training.md
This PR added the talent plan announcement in the blog.
=> blog: add talent plan article for blog

content/blog/talent-training.md
Just a fix of incorrect line wrap.
=> talent-training: fix line wrap

config.yaml, layouts/index.redirects
Correct "output" to "outputs" and align it properly with tabs.
Also add status codes to force a couple redirects to always happen.
=> Fixup redirects

config.yaml, layouts/index.redirects
Should point `/docs` to `/docs/{{ $latest }}/concepts/overview/ ` and fix a menu link.
=> Better landings for some URLs.

content/blog/client-futures.md
=> Add the migrating futures blog post

content/blog/monthly-july-19.md
=> Add July 19 issue of TMIT

content/docs/3.0/concepts/overview.md, content/docs/3.0/reference/clients/introduction.md, content/docs/3.0/reference/query-layers.md, data/features.yaml, layouts/index.html, layouts/shortcodes/features.html
This PR rounds out the overview a bit by adding some more starter context, and reduces the amount of one-line paragraphs to create a more pleasant reading experience.
It also adds a separate page listing all known query layers (to expand on later) and expands the features page with some new ideas.
=> Refactor overview and add query layers page

layouts/partials/footer.html
=> footer: fix the link for Overview in footer

README.md
Fixes #64 
(Trivial PR, merge with 1 review)
=> Fix README link.

assets/sass/style.sass, layouts/docs/single.html
Fixes code blocks overflowing if they contain long strings, also helps with our responsiveness on several screen sizes.
=> Fix code overflow

content/docs/3.0/tasks/monitor/tikv-cluster.md, content/docs/deep-dive/distributed-sql/dist-sql.md
1. Fixup tikv-cluster.md document picture link.
2. Remove dist-sql.md document markdown picture link.
Signed-off-by: chengchen <cc8602@gmail.com>
=> Fixup documents picture link.

.github/ISSUE_TEMPLATE/change-request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> templates: add issue and PR templates for repo

content/blog/monthly-august-19.md
=> August tmit

Dockerfile, README.md
=> Add Docker build instructions

content/docs/3.0/tasks/deploy/docker-compose.md
We were replicating a lot of content from the official Docker Compose guide. and this guide had some out of date information (eg we have docker swarm now!)
#81
=> Trim duplication in docker compose guide

layouts/index.html
Remove the incubating announcement has been up since May, so we can probably remove it. :) I commented it out as we'll use it in the future for release announcements etc.
#37
=> Remove the incubating announcement

content/docs/3.0/tasks/configure/limit.md, content/docs/3.0/tasks/configure/namespace.md, content/docs/3.0/tasks/configure/region-merge.md, content/docs/3.0/tasks/configure/titan.md, content/docs/3.0/tasks/configure/topology.md
Reviewed and made a number of small fixes or cleanups in the config section.
=> Small config section fixes

layouts/index.redirects
Fix the security link we have in order to satisfy the criteria for the CII badge.
Related to #17
=> Fix /security link

content/docs/3.0/tasks/deploy/ansible.md
Just some minor touch ups to the Ansible guide
=> Minor fixes to Ansible guide

layouts/partials/navbar.html
This PR makes our menus usable on mobile. Previously on mobiles you could not access submenus like Deep Dive. This PR makes them all unrolled so the user can select what they wish.
=> Expand sub menu dropdowns on touch

content/docs/3.0/faq/faq.md
Signed-off-by: Samantha Blowers <blowers.sam@gmail.com>
wording/grammar in FAQ
no
all?
=> fix grammar/wording

content/docs/3.0/tasks/deploy/introduction.md
Refined and trimmed some content in the deploy introduction to readers are getting the right information, and trying to build greater understanding.
=> Refine the deployment intro

content/docs/3.0/faq/faq.md
Updated the right link for quick start
=> update link for quick start

content/docs/3.0/tasks/introduction.md
=> Fix try links

config.yaml, content/docs/3.0/contribute/contribute-to-tikv.md
Remove our discourse links so we can decommission it.
=> remove forum links

CONTRIBUTING.md
@winkyao and @gingerkidney asked for some easier contributing guides for this site. :)
=> Refine contributing doc

content/blog/monthly-october-2019.md
=> Add monthly for october 2019

content/docs/3.0/tasks/configure/security.md
Adds some clarification/working/tone changes around TLS setup and prunes out a dead link for a simple inline script.
Nope
3.0
=> Expand security section and prune dead link

content/docs/3.0/reference/contribute.md, content/docs/3.0/reference/faq.md, content/docs/3.0/reference/tools/introduction.md, content/docs/3.0/tasks/configure/limit.md, content/docs/3.0/tasks/configure/namespace.md, content/docs/3.0/tasks/configure/region-merge.md, content/docs/3.0/tasks/deploy/binary.md, content/docs/3.0/tasks/deploy/docker.md, content/docs/3.0/tasks/scale/introduction.md
Resolves a few things I think we overlooked.
Before: 
After:
=> Fix a few broken links and simplify the menus

content/docs/3.0/tasks/deploy/introduction.md
Be much more explicit about supported OS. Helps with #110
=> Add OS information to reqs

content/docs/3.0/tasks/deploy/binary.md, content/docs/3.0/tasks/deploy/introduction.md
=> Fix the try link

content/blog/monthly-december-2019.md
=> Add Dec Monthly

config.yaml
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>
Fixed an invalid link
@dcalvin PTLA, thanks!
=> fix: replace an invalid link

content/blog/monthly-january-2020.md
=> add monthly for January 2020

content/blog/monthly-january-2020.md
=> update the opening paragraph

content/blog/lease-read.md
Add a blog post of lease read
N/A
master
=> Add a blog post of lease read

content/docs/3.0/reference/clients/go.md, content/docs/3.1-beta/reference/clients/go.md
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>
Fix the outdated code in the examples
https://github.com/pingcap/pd/issues/2148
* 3.0
* 3.1-beta
=> example: fix the outdated code

layouts/_default/baseof.html, layouts/deep-dive/single.html, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/footer.html, layouts/partials/navbar.html
update regex to match dev version
=> update version find regex

content/blog/monthly-march-2020.md
add a monthly blog for March 2020
N/A
=> add monthly March 2020

content/blog/RocksDB-in-TiKV.md
=> Fix links in RocksDB in TiKV

data/adopters.yaml
=> update the list of adopters

content/docs/dev/tasks/configure/security.md
Signed-off-by: TXXT <hunterlxt@live.com>
update allow cert config
https://github.com/tikv/tikv/pull/7134
https://github.com/tikv/tikv/commit/e1b456e3debee40fbbbc38ebdc3ed0ddae9f3b6d
TiKV master, release 4.0
=> security doc: update allow cert config

content/docs/3.0/releases/3.0-ga.md, content/docs/3.0/releases/introduction.md, content/docs/3.0/roadmap.md, content/docs/dev/releases/3.0-ga.md, content/docs/dev/releases/4.0.0-rc.md, content/docs/dev/releases/introduction.md, content/docs/dev/roadmap.md
Signed-off-by: anotherrachel <wangyajing@pingcap.com>
This PR adds release notes too v3.0 and dev.
N/A
v3.0 and dev
=> add release notes

content/docs/dev/tasks/monitor/key-metrics.md
Signed-off-by: TXXT <hunterlxt@live.com>
Update tikv key metric
close https://github.com/pingcap/docs-cn/issues/2801
4.0 master
=> Update tikv key metric

content/blog/monthly-april-2020.md
=> add-monthly-april-2020

content/deep-dive/consensus-algorithm/introduction.md
Signed-off-by: Youwithouto <youwithouto.z@gmail.com>
The first paragraph in the [Consensus algorithm](https://tikv.org/deep-dive/consensus-algorithm/introduction/) Section is a bit unclear to me. And I think it tries to paraphrase the first paragraph of the `Hold on—what is consensus?` Section of the [Raft doc](https://raft.github.io/).
Please reject this PR if my understanding is incorrect.
=> Update first paragraph of "Consensus Algorithm"

content/blog/implement-raft-in-rust.md
=> fix errors in Implement raft in rust

content/blog/talent-training.md, content/docs/3.0/tasks/deploy/ansible.md, content/docs/3.0/tasks/monitor/key-metrics.md
Correct links as they caused a bit of confusion.
Solved #146 and #158
=> Correct links

content/blog/tikv-4.0-ga.md
=> add tikv 4.0 ga

content/blog/monthly-june-2020.md
=> add monthly june 2020

content/docs/3.0/tasks/try/docker-stack.md, content/docs/3.0/tasks/try/introduction.md, content/docs/3.0/tasks/try/tikv-operator.md, content/docs/4.0/tasks/try/docker-stack.md, content/docs/4.0/tasks/try/introduction.md, content/docs/4.0/tasks/try/tikv-operator.md, content/docs/dev/tasks/try/docker-stack.md, content/docs/dev/tasks/try/introduction.md, content/docs/dev/tasks/try/tikv-operator.md
This PR:
* add `tikv-operator.md`
* reorganize `Try` section
https://github.com/tikv/tikv-operator/pull/8/
v3.0, v4.0, dev
=> add tikv-operator doc

content/blog/announcing-sig-txn.md
Please publish on Tuesday 2020-07-21.
PTAL @WT-Liu @dcalvin
=> blog: add announcment post for txn sig

content/blog/monthly-july-2020.md
=> add monthly

content/blog/rustconf-20.md
=> Add blog post about rustconf

content/blog/monthly-august-2020.md
=> add monthly august 2020

content/blog/tikv-4.0-ga.md
=> fix errors

assets/sass/style.sass, layouts/index.html
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>
Add section for cncf graduate promotion
=> chore: add cncf project promotion

content/community/community.md, content/community/sig-scheduling.md
Add some information about the scheduling SIG.
N/A
N/A
=> add scheduling sig

content/blog/generics-compile-time-rust.md
=> add generics compile-time in rust

content/blog/monthly-spet-2020.md
=> add monthly spet 2020

content/docs/3.0/tasks/configure/rocksdb.md, content/docs/3.0/tasks/deploy/introduction.md, content/docs/3.0/tasks/deploy/prerequisites.md, content/docs/3.0/tasks/try/docker-stack.md, content/docs/4.0/tasks/configure/rocksdb.md, content/docs/4.0/tasks/deploy/introduction.md, content/docs/4.0/tasks/deploy/prerequisites.md, content/docs/4.0/tasks/try/docker-stack.md, content/docs/dev/concepts/architecture.md, content/docs/dev/tasks/configure/limit.md, content/docs/dev/tasks/configure/region-merge.md, content/docs/dev/tasks/configure/rocksdb.md, content/docs/dev/tasks/configure/security.md, content/docs/dev/tasks/configure/topology.md, content/docs/dev/tasks/deploy/introduction.md, content/docs/dev/tasks/deploy/prerequisites.md, content/docs/dev/tasks/try/docker-stack.md
- Add more options to RocksDB Config
- Fix broken links
- Fix broken diagram link
- Fix typos
- Update words to standard capitalization
- Split the Deploy `introduction.md` into two files: `introduction.md` with new intro content and `prerequisites.md`
Related link: https://docs.pingcap.com/tidb/stable/tikv-configuration-file#rocksdb
dev, v4.0, v3.0
=> Update config and deploy, fix broken links and typos

content/docs/3.0/reference/tools/pd-ctl.md, content/docs/3.0/tasks/configure/introduction.md, content/docs/3.0/tasks/configure/titan.md, content/docs/3.0/tasks/deploy/ansible.md, content/docs/4.0/reference/tools/pd-ctl.md, content/docs/4.0/tasks/configure/coprocessor.md, content/docs/4.0/tasks/configure/grpc.md, content/docs/4.0/tasks/configure/introduction.md, content/docs/4.0/tasks/configure/limit.md, content/docs/4.0/tasks/configure/pd.md, content/docs/4.0/tasks/configure/raftstore.md, content/docs/4.0/tasks/configure/region-merge.md, content/docs/4.0/tasks/configure/storage.md, content/docs/4.0/tasks/configure/titan.md, content/docs/4.0/tasks/deploy/ansible.md, content/docs/dev/reference/tools/pd-ctl.md, content/docs/dev/tasks/configure/coprocessor.md, content/docs/dev/tasks/configure/grpc.md, content/docs/dev/tasks/configure/introduction.md, content/docs/dev/tasks/configure/limit.md, content/docs/dev/tasks/configure/pd.md, content/docs/dev/tasks/configure/raftstore.md, content/docs/dev/tasks/configure/security.md, content/docs/dev/tasks/configure/storage.md, content/docs/dev/tasks/configure/titan.md, content/docs/dev/tasks/deploy/ansible.md
- Add five config files to dev & 4.0: `pd.md`, `raftstore.md`, `coprocessor.md`, `storage.md`, `grpc.md`
- Add three more config parameters to `titan.md`
- Add new config files to the list in `introduction.md` of Config
- Set display order for all the 12 config files
- Fix typos and format in 3.0
Related source: [TiKV Configuration File | PingCAP Docs](https://docs.pingcap.com/tidb/stable/tikv-configuration-file#storage)
**Note:** I didn't keep parameters for TiDB Dashboard in the newly added config files and removed all ref links to other documents in [docs.pingcap.com](https://docs.pingcap.com/tidb/stable/).
- Content changes for dev & 4.0
- Typo and format fix for 3.0
=> Add five config files to dev & 4.0

content/blog/sig-txn-reading-group-nov-20.md
Adds a blog post on the sig-txn reading group
no
n/a
PTAL @dcalvin
=> blog: add post on sig-txn reading group

content/docs/3.0/tasks/introduction.md, content/docs/4.0/tasks/introduction.md, content/docs/dev/tasks/introduction.md
Signed-off-by: Charlotte Liu <37295236+CharLotteiu@users.noreply.github.com>
Fix dead links in the tasks introduction page to close https://github.com/tikv/tikv/issues/9033.
https://github.com/tikv/tikv/issues/9033
3.0, 4.0 and dev.
=> fix dead links in tasks introduction

content/blog/my-experience-in-flx-for-tikv.md
=> update blog title

content/blog/client-rust-0.1.md
Adds a blog post to announce the 0.1 release of the Rust client
PTAL @dcalvin @WT-Liu
=> blog: rust client 0.1 release

content/docs/5.1/concepts/tikv-in-5-minutes.md, content/docs/5.1/deploy/benchmark/benchmark.md, content/docs/5.1/deploy/configure/configure.md, content/docs/5.1/deploy/deploy.md, content/docs/5.1/deploy/install/install.md, content/docs/5.1/deploy/install/prerequisites.md, content/docs/5.1/deploy/install/production.md, content/docs/5.1/deploy/install/test.md, content/docs/5.1/deploy/install/verify.md, content/docs/5.1/deploy/monitor/monitor.md, content/docs/5.1/deploy/operate/operate.md
This PR covers `Deploy ` -> `Install TiKV`
v5.1
=> add doc for v5.1: Deploy -> Install TiKV

content/docs/5.1/deploy/operate/maintain.md, content/docs/5.1/deploy/operate/operate.md, content/docs/5.1/deploy/operate/scale.md, content/docs/5.1/deploy/operate/upgrade.md
This PR covers `Deploy ` -> `Operate TiKV`
v5.1
=> add doc for v5.1: Deploy -> Operate TiKV

content/docs/5.1/develop/clients/cpp.md, content/docs/5.1/develop/clients/go.md, content/docs/5.1/develop/clients/introduction.md, content/docs/5.1/develop/clients/java.md, content/docs/5.1/develop/clients/python.md, content/docs/5.1/develop/clients/rust.md, content/docs/5.1/develop/develop.md
This PR covers `Develop` -> `TiKV Clients`
v5.1
=> add docs for v5.1: Develop -> TiKV Clients

content/docs/5.1/reference/TiUP.md, content/docs/5.1/reference/faq.md, content/docs/5.1/reference/introduction.md, content/docs/5.1/reference/query-layers.md
This PR covers `Reference` -> `Query Layers` + `TiUP` + `FAQs`
This PR references to 
- https://tikv.org/docs/4.0/reference/query-layers/
- https://tikv.org/docs/4.0/reference/faq/
v5.1
=> add docs for v5.1: reference -> Query Layers + TiUP + FAQs 

content/docs/5.1/reference/CLI/introduction.md, content/docs/5.1/reference/CLI/pd-ctl.md, content/docs/5.1/reference/CLI/pd-recover.md, content/docs/5.1/reference/CLI/tikv-ctl.md, content/docs/5.1/reference/introduction.md
This PR covers `Reference` -> `CLI`
This PR references to
- https://docs.pingcap.com/tidb/stable/pd-control
- https://docs.pingcap.com/tidb/stable/tikv-control
- https://docs.pingcap.com/tidb/stable/pd-recover
v5.1
=> add docs for v5.1: reference -> CLI 

content/docs/5.1/concepts/explore-tikv-features/cas.md, content/docs/5.1/concepts/explore-tikv-features/replication-and-rebalancing.md, content/docs/5.1/concepts/explore-tikv-features/ttl.md, content/docs/5.1/concepts/tikv-in-5-minutes.md, content/docs/5.1/deploy/install/test.md
This PR includes: 
- `Get Started` -> `CAS`: use java instead of rust
- `Get Started` -> `TiKV in 5 Minutes`: update java example
- fix tiup version issue
v5.1
=> docs for v5.1: update Features -> CAS example

content/docs/5.1/concepts/explore-tikv-features/cas.md, content/docs/5.1/develop/clients/introduction.md, content/docs/5.1/develop/rawkv/cas.md, content/docs/5.1/develop/rawkv/get-put-delete.md, content/docs/5.1/develop/rawkv/introduction.md, content/docs/5.1/develop/rawkv/put-get-delete.md, content/docs/5.1/develop/rawkv/scan.md, content/docs/5.1/develop/rawkv/ttl.md
This PR covers `Develop` -> `RawKV`
v5.1
=> add docs for v5.1: Develop -> RawKV

layouts/index.html
=> fix case studies link

assets/sass/style.sass
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>
=> ui: update footer link hover color

content/docs/5.1/concepts/tikv-in-5-minutes.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
Modify TiKV in 5 Minutes
Related PR: https://github.com/tikv/website/pull/224
=> Modify TiKV in 5 Minutes

content/docs/5.1/deploy/configure/coprocessor.md, content/docs/5.1/deploy/configure/grpc.md, content/docs/5.1/deploy/configure/limit.md, content/docs/5.1/deploy/configure/raftstore.md, content/docs/5.1/deploy/configure/region-merge.md, content/docs/5.1/deploy/configure/rocksdb.md, content/docs/5.1/deploy/configure/security.md, content/docs/5.1/deploy/configure/storage.md, content/docs/5.1/deploy/configure/titan.md, content/docs/5.1/deploy/configure/topology.md
fix duplicate Title: Storage
- content/docs/5.1/reference/architecture/storage.md
- content/docs/5.1/deploy/config/storage.md
=> fix duplicate Title: Storage

content/docs/5.1/develop/clients/rust.md
Signed-off-by: Charlotte Liu <37295236+CharLotteiu@users.noreply.github.com>
Optimize the expressions in clients/rust.md
https://github.com/tikv/website/pull/239/
v5.1
=> optimize rust.md

content/docs/5.1/develop/clients/rust.md
Signed-off-by: Liuxiaozhen12 <liuxiaozhen@pingcap.com>
https://github.com/tikv/website/pull/264
v5.1
=> minor changes in rust.md

content/docs/5.1/concepts/explore-tikv-features/cas.md, content/docs/5.1/deploy/monitor/monitor.md, content/docs/5.1/reference/CLI/introduction.md, content/docs/5.1/reference/architecture/overview.md
I've reviewed and updated the following four TiKV docs.
- CAS on RawKV
- reference/architecture/overview.md
- reference/CLI/introduction.md
- Monitor and Alert
=> Review and update four TiKV docs

content/docs/5.1/deploy/operate/operate.md, content/docs/5.1/develop/clients/cpp.md, content/docs/5.1/develop/rawkv/ttl.md, content/docs/5.1/reference/TiUP.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
Batch update TiKV docs
=> Batch update TiKV docs

content/docs/5.1/concepts/explore-tikv-features/ttl.md
Signed-off-by: Liuxiaozhen12 <liuxiaozhen@pingcap.com>
add an explanation of TTL
https://github.com/tikv/website/pull/257
TTL 指的是 Time To Live。
如果不用 TTL，那么往 TiKV 写入的数据，会一直存在在 TiKV 中，除非有人删除。
如果使用 TTL，例如设置某个 key 的 TTL = 1 小时，那边 1 小时后这个数据会被 TiKV 自动删除。
=> add an explanation of TTL

content/docs/5.1/deploy/configure/introduction.md, content/docs/5.1/develop/clients/java.md, content/docs/5.1/develop/clients/python.md
Signed-off-by: Liuxiaozhen12 <liuxiaozhen@pingcap.com>
https://github.com/tikv/website/pull/239
https://github.com/tikv/website/pull/233
=> modify java.md, python.md, and configure-introduction.md

content/docs/5.1/concepts/explore-tikv-features/distributed-transaction.md, content/docs/5.1/develop/rawkv/cas.md, content/docs/5.1/develop/rawkv/get-put-delete.md
Signed-off-by: Liuxiaozhen12 <liuxiaozhen@pingcap.com>
modify get-put-delete.md and cas.md
https://github.com/tikv/website/pull/243
=> modify get-put-delete.md and cas.md

content/docs/5.1/concepts/explore-tikv-features/fault-tolerance.md, content/docs/5.1/reference/architecture/overview.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
Improve the fault tolerance doc.
The original PR: https://github.com/tikv/website/pull/246
=> Improve the fault tolerance doc

content/docs/5.1/concepts/overview.md, content/docs/5.1/concepts/whats-next.md, content/docs/5.1/deploy/deploy.md, content/docs/5.1/develop/clients/introduction.md, content/docs/5.1/develop/develop.md, content/docs/5.1/develop/rawkv/introduction.md
This PR includes 
1. `Get Started` ->  `What's Next`
2. `Overview`
v5.1
=> docs for v5.1: add `Get Started -> What's Next` and `Overview`

layouts/deep-dive/single.html, layouts/docs/single.html
remove `We are currently refactoring our documentation.`
https://github.com/tikv/website/issues/227
=> remove `We are currently refactoring our documentation.`

content/docs/5.1/concepts/overview.md, content/docs/5.1/concepts/whats-next.md, content/docs/5.1/develop/clients/cpp.md, content/docs/5.1/develop/clients/go.md, content/docs/5.1/develop/clients/introduction.md, content/docs/5.1/develop/clients/python.md, content/docs/5.1/develop/develop.md, content/docs/5.1/reference/architecture/overview.md
Signed-off-by: qiancai <qqzczy@126.com>
In this PR, I've reviewed and updated the changes made in https://github.com/tikv/website/pull/245 from the writing perspective.
=> review and update docs changed in #245

content/docs/5.1/concepts/overview.md, content/docs/5.1/develop/clients/rust.md
TiKV Rust Client is still in the proof-of-concept stage and under development.
=> Add Rust-Client status

content/docs/5.1/deploy/performance/instructions.md, content/docs/5.1/deploy/performance/overview.md, content/docs/5.1/deploy/performance/performance.md
Signed-off-by: qiancai <qqzczy@126.com>
In this PR, I've reviewed and updated doc changes made in https://github.com/tikv/website/pull/271 from the user perspective.
=> Review and update changes in "tikv benchmark overview #271"

content/docs/5.1/deploy/performance/instructions.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
Improve benchmark instruction doc
https://github.com/tikv/website/pull/255
=> Improve benchmark instruction doc

content/blog/tikv-on-juicefs.md
Signed-off-by: Mila Wu <wumila1996@gmail.com>
=> chore: fix juicefs blog issues

content/docs/5.1/deploy/install/prerequisites.md
Change wording for "Network requirements"
No
=> Change wording for "Network requirements"

content/docs/5.1/concepts/tikv-in-5-minutes.md
update client java download link
close https://github.com/tikv/website/issues/285
=> update client java download link

content/docs/5.1/concepts/tikv-in-5-minutes.md
update tikv python client install steps
close https://github.com/tikv/website/issues/286
=> update tikv python client install steps

content/docs/5.1/deploy/configure/region-merge.md
fix typo from `PD will start the Region Merge process that merges the bigger region into the smaller region.` to `PD will start the Region Merge process that merges the smaller regions into the bigger region.`
=> fix region merge doc

content/docs/5.1/deploy/install/production.md, content/docs/5.1/deploy/install/test.md, content/docs/5.1/deploy/operate/upgrade.md
Signed-off-by: shichun-0415 <lishichun@pingcap.com>
Update wording after peer review
No
=> Update wording after peer review

content/docs/5.1/deploy/operate/scale.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
Modified the doc "content/docs/5.1/deploy/operate/scale.md"
https://github.com/tikv/website/pull/232
v5.1
=> modify the doc "scale"

content/docs/5.1/deploy/install/verify.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
Modified the doc "verify.md"
https://github.com/tikv/website/pull/231
v5.1
=> modify the doc "verify"

content/docs/5.1/deploy/monitor/key-metrics.md, content/docs/5.1/reference/faq.md, content/docs/5.1/reference/query-layers.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
Modified the following three docs:
- [FAQs](https://tikv.org/docs/5.1/reference/faq/) (faq.md)
- [Query Layers](https://tikv.org/docs/5.1/reference/query-layers/) (query-layers.md)
- [Key Metrics](https://tikv.org/docs/5.1/deploy/monitor/key-metrics/) (key-metrics.md)
[#234](https://github.com/tikv/website/pull/234), [238](https://github.com/tikv/website/pull/238)
v5.1
=> modify docs of "references" and "key metrics"

content/deep-dive/rpc/protobuf.md
=> fix typo Probobufs -> Protobuf

data/getStarted.yaml
Fixed link to benchmarks and performance
Getting started -> Benchmark and Performance ->
https://tikv.org/docs/5.1/deploy/benchmark/benchmark/
Broken Link
5.1
=> Fix broken benchmarks link

content/docs/5.1/reference/CLI/tikv-ctl.md, content/docs/dev/reference/tools/tikv-ctl.md
Replacing the deprecated `--db` with `--data-dir`
Closes #306 
5.1 and up
=> Replace --db with --data-dir

content/docs/dev/reference/clients/java.md, content/docs/dev/tasks/export/introduction.md
Add documentation for TiKV bulk export.
https://github.com/tikv/tikv/issues/11007
5.3.0
=> Add documentation for export

content/docs/3.0/tasks/scale/introduction.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
Changed a wrong URL in "content/docs/3.0/tasks/scale/introduction.md" doc according to "Ask Docs" issue.
=> fix a 404 url

content/blog/double-system-read-throughput.md
Signed-off-by: Mila Wu <wumila1996@gmail.com>
Fix a typo in the blog.
=> chores: fix-throughput-typo

content/blog/client_node_and_cncf_mentorship.md
Signed-off-by: Jiaxiao Zhou <jiazho@microsoft.com>
I added a blog about my experience with CNCF LFX mentorship and my contributions to client-node repo.
No
=> added client-node and CNCF LFX Mentorship exp blog

Dockerfile
Signed-off-by: xkenmon <xkenmon@xkenmon.com>
Fix `make docker` error.
#225 
All version.
=> Add git dependency to alpine

content/deep-dive/distributed-transaction/percolator.md
Fix a symbol usage mistake that `v"write` to `v:write`
=> update v"write to v:write

config.yaml
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
Fix broken branding link.
=> community: fix branding link

content/adopters.md
Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>
Add tidbcloud to adopters
=> Add products or services providers to adopters page

content/adopters.md
=> Add tidbcloud to adopters

content/docs/dev/concepts/explore-tikv-features/backup-restore.md, content/docs/dev/develop/rawkv/checksum.md, content/docs/dev/develop/rawkv/introduction.md
Add rawkv checksum doc.
dev
preview is [here](https://deploy-preview-329--tikv.netlify.app/)
=> Add rawkv checksum doc

content/docs/dev/concepts/explore-tikv-features/backup-restore.md
Signed-off-by: haojinming <jinming.hao@pingcap.com>
=> Add performance metric of tikv-br

content/community/community.md
- Correct the TIKV-security link
- Remove The monthly meetings info as that doesn't happen anymore
- Update the Tidis URL
- Update the CNCF Code of Conduct URL
=> Update community page

content/deep-dive/consensus-algorithm/consistency-availability-partitioning.md
Make the PACELC start with a P for partitioning
=> Update PACELC explanation

content/deep-dive/consensus-algorithm/raft.md
Signed-off-by: Ping Yu <yuping@pingcap.com>
Fix broken link of Raft thesis.
Preview: https://deploy-preview-338--tikv.netlify.app/deep-dive/consensus-algorithm/raft/
Close: #200 
All.
=> deep-dive: fix broken link of Raft thesis

content/docs/6.5/new-features/overview.md, content/docs/dev/new-features/overview.md
Add release notes for v6.5.1 & v6.6.0.
Preview:
- v6.5.1: https://deploy-preview-341--tikv.netlify.app/docs/6.5/new-features/overview/
- v6.6.0: https://deploy-preview-341--tikv.netlify.app/docs/dev/new-features/overview/
No.
v6.5 + v6.6
=> Add release notes for v6.5.1 & v6.6.0

content/docs/dev/concepts/explore-tikv-features/cdc/cdc-cn.md
Add docs for filter feature of RawKV CDC.
Preview: https://deploy-preview-346--tikv.netlify.app/docs/dev/concepts/explore-tikv-features/cdc/cdc-cn/#changefeed-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
https://github.com/tikv/migration/pull/349
TiKV-CDC v1.2.0
=> Add docs for RawKV CDC filter (cn)

content/deep-dive/distributed-transaction/percolator.md
- Fix broken link of `Percolator`.
Preview: https://deploy-preview-356--tikv.netlify.app/deep-dive/distributed-transaction/percolator/
All
=> deep-dive: Fix broken link of Percolator
