tikv/website

assets/sass/style.sass, content/deep-dive/consensus-algorithm/consistency-availability-partitioning.md, content/deep-dive/distributed-sql/dist-sql.md, content/deep-dive/distributed-transaction/locking.md, content/deep-dive/key-value-engine/b-tree-vs-lsm.md, content/deep-dive/resource-scheduling/_index.md, content/deep-dive/resource-scheduling/kubernetes.md, layouts/deep-dive/list.html, layouts/partials/deep-dive/toc.html
This refines the deep-dive TOC with a bit of font size change and some title shortening to fit nicer on more screen sizes.
Half Screen:
Narrower Screen:
Full HD:
Mobile Snap:
=> Make Deep Dive TOC fit on more screen sizes

data/adopters.yaml
Removed eleme user case for it has been acquired by Alibaba.
=> remove eleme user case for marketing reasons

layouts/index.redirects, layouts/partials/navbar.html
Adds a convenient chat redirect at `tikv.org/chat` so we don't need this complicated Slack link.
=> Add chat redirect

Makefile
Currently if we merge a PR with some future date it won't build until that date. This changes that so it builds all future dates as well.
=> Build future posts on publish

content/docs/3.0/reference/tools/pd-ctl.md
This PR updated the usage for  `check miss-peer` in PD ctl tool
Related PRs: 
https://github.com/pingcap/docs-cn/pull/1824
https://github.com/pingcap/docs/pull/1508
=> reference/pd-ctl: update region miss-peer check usage

layouts/index.redirects
Slack has a per-link limit on number of clicks so we need to refresh this periodically.
I sigh in disappointment that this PR needs to exist.
Trivial PR so just merge with 1 review. :)
=> Refresh chat links

Makefile, README.md
Addresses #109 in a slightly different way, making it easier to use `docker` based workflows without needing `docker-compose` since it's not as commonly installed.
=> Add docker make task and more docs

content/deep-dive/distributed-transaction/percolator.md
=> Update Percolator paper URL

CONTRIBUTING.md
Signed-off-by: Youwithouto <youwithouto.z@gmail.com>
The `upstream URL` in the `CONTRIBUTING.md` file is incorrect. 
This fix changes the `upstream URL` from `git@github.com:tikv/tikv.git` to `git@github.com:tikv/website.git`.
=> Change the upstream URL to the correct one

content/deep-dive/consensus-algorithm/introduction.md
Signed-off-by: Youwithouto <youwithouto.z@gmail.com>
Remove 'a' from the sentence "Raft is generally seen as a more understandable and simpler to implement than Paxos." in the [Consensus algorithm section](https://tikv.org/deep-dive/consensus-algorithm/introduction/) of the doc website.
=> Remove 'a' to fix a grammar mistake

content/docs/3.0/tasks/try.md
https://tikv.org/docs/3.0/tasks/try/ has to dead links that should point to the client docs.
=> correct path to client docs

layouts/partials/blog/hero.html, layouts/partials/meta.html
Added "Subscribe via RSS" link right after the blog title. screenshots :point_down: 
Also added a `<link>` tag in `<head>` that points to the RSS feed URL. This helps RSS readers in picking up the RSS feed URL just by typing the base URL (E.g. https://tikv.org). Without this tag, the user may need to type the full URL (https://tikv.org/blog/index.xml) in the RSS feed reader application.
#167 
N/A
=> Adds RSS feed for the blog

config.yaml, content/community/community.md, content/community/sig-coprocessor.md, content/community/sig-engine.md, content/community/sig-raft.md, content/community/sig-transaction.md
This PR adds a small community page (fixing a broken link from the community menu in the process - closes #171). From there, there is a link to a basic page for each SIG. We will use the transaction sig page as a landing page for attracting new members.
PTAL @dcalvin
=> Add a community page and a page for each SIG

content/deep-dive/distributed-transaction/percolator.md
Fixed a small typo in a local anchor.
None
The faulty anchor can be viewed on [https://tikv.org/deep-dive/distributed-transaction/percolator/](https://tikv.org/deep-dive/distributed-transaction/percolator/). When clicking on [Percolator in TiKV](https://tikv.org/deep-dive/distributed-transaction/percolator/#Percolator-in-TiKV), nothing is happening.
Extract of the generated HTML for the link:
```html
can skip this section and go directly to <a href=#Percolator-in-TiKV>Percolator in TiKV</a>
```
Extract of the generated HTML for the anchor:
```html
<h2 id=percolator-in-tikv>Percolator in TiKV</h2>
```
=> fix(percolator): right anchor

content/adopters.md, content/docs/3.0/reference/tools/tikv-ctl.md, content/docs/3.0/tasks/configure/rocksdb.md, content/docs/3.0/tasks/scale/introduction.md, content/docs/4.0/reference/tools/tikv-ctl.md, content/docs/4.0/tasks/configure/grpc.md, content/docs/4.0/tasks/configure/pd.md, content/docs/4.0/tasks/configure/rocksdb.md, content/docs/4.0/tasks/configure/storage.md, content/docs/4.0/tasks/scale/introduction.md, content/docs/dev/reference/tools/tikv-ctl.md, content/docs/dev/tasks/configure/grpc.md, content/docs/dev/tasks/configure/introduction.md, content/docs/dev/tasks/configure/pd.md, content/docs/dev/tasks/configure/rocksdb.md, content/docs/dev/tasks/configure/storage.md, content/docs/dev/tasks/configure/synchronous-replication.md, content/docs/dev/tasks/scale/introduction.md
This PR migrates applicable changes from https://github.com/tikv/tikv/commits/master/docs, including:
- Add `synchronous-replication.md` to dev (confirmed with @BusyJay)
- Update multiple config files by fixing format, adding new items, or removing outdated items (confirmed with multiple TiKV developers)
- Update `adopters.md` to the latest version (@WT-Liu FYI.)
- Fix all tikv ports in all versions: `21060` -> `20160`, `21061` -> `20161` (confirmed with @nolouch)
- https://github.com/tikv/tikv/pull/8863
- https://github.com/tikv/tikv/pull/8825
- https://github.com/tikv/tikv/pull/8283
- https://github.com/tikv/tikv/pull/7740
- https://github.com/tikv/tikv/pull/6397
- https://github.com/tikv/tikv/pull/5818
- https://github.com/tikv/tikv/pull/5827 …
=> Add and update multiple config and tools docs

config.yaml
`unsafe` is needed to render table with multilines cell properly,
for example in deep-dive/distributed-transaction/percolator/,
refer to https://gohugo.io/getting-started/configuration-markup/
for more information.
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>
=> enable goldmark `unsafe` renderer option

content/docs/4.0/reference/clients/go.md, content/docs/dev/reference/clients/go.md
The TiKV client in the TiDB repo contains special logic that is unsuitable for KV usages. See https://github.com/pingcap/tidb/issues/22287.
Then, [a branch](https://github.com/pingcap/tidb/tree/kv-only-4.0) is forked from the release-4.0 branch of TiDB to remove the logic. In the doc, we should recommend the user using the client without TiDB related logic.
https://github.com/pingcap/tidb/issues/22287
=> Use special branch of TiDB for Go client

config.yaml
Use v5.1 as default document.
https://github.com/tikv/website/issues/227
=> use v5.1 as default document

content/docs/5.1/deploy/performance/instructions.md, content/docs/5.1/deploy/performance/overview.md
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
=> docs: fix dead link and info macro format in benchmark

content/docs/4.0/tasks/try/tikv-operator.md
`helm install --namespace tikv-operator tikv-operator pingcap/tikv-operator --version v0.1.0` is for creating operator, not creating namespace. I remove it from create namespace section.
IDK
4.0
=> Remove duplicate command in create namespace section of operator doc

content/deep-dive/distributed-transaction/optimized-percolator.md
It means that Txn1's request `commit_ts` after Txn2's requested `start_ts`,so Txn1's  `commit_ts` > Txn2's  `start_ts`.
=> fix wrong name.

content/docs/3.0/tasks/try/docker-stack.md, content/docs/4.0/tasks/try/docker-stack.md, content/docs/dev/tasks/try/docker-stack.md
The `src/main.rs` in https://tikv.org/docs/4.0/tasks/try/docker-stack/ does not compile. It fails with:
```
the `?` operator cannot be applied to type `impl std::future::Future`
help: consider using `.await` here: `RawClient::new(config).await?`
```
Adding `await` as the compiler suggests fixes the issue.
=> Fix main.rs in the docker stack example

content/docs/4.0/tasks/try/docker-stack.md
This fixes the `Dockerfile` in 4.0/try/docker-stack.md, and updates the documentation to remove the warning about installing nightly rust.
Resolves #214.
4.0
=> Fix 4.0/try/docker-stack Dockerfile

content/docs/7.1/deploy/configure/security.md, content/docs/dev/deploy/configure/security.md
Update the TLS config docs for TiKV Clients, including rust/go/java, they all support TLS now. 
dev, 7.1
=> client java/rust/go should support TLS

content/docs/6.1/deploy/configure/topology.md, content/docs/6.5/deploy/configure/topology.md, content/docs/7.1/deploy/configure/topology.md, content/docs/dev/deploy/configure/topology.md
The labels are not a string.
```
invalid auto generated configuration file /home/dvaneeden/.tiup/data/UaWnp6Q/tikv-0/tikv.toml, err invalid type: string "foo=bar", expected a map for key `server.labels` at line 8 column 10
```
Alternative syntax from https://docs.pingcap.com/tidb/stable/schedule-replicas-by-topology-labels#configure-labels-for-tikv-and-tiflash
```
[server.labels]
zone = "<zone>"
dc = "<dc>"
rack = "<rack>"
host = "<host>"
```
This doesn't work:
```
tiup playground --kv.config <(echo -en "[server]\nlabels = \"foo=bar\"\n") v8.5.0
```
This does:
```
tiup playground --kv.config <(echo -en "[server]\nlabels = {foo=\"bar\"}\n") v8.5.0
```
=> Fix labels config syntax
